"""add taxonomy node topic terms

Revision ID: 0f719dabebd7
Revises: d6980dd4a9a6
Create Date: 2026-04-13 14:55:06.933078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f719dabebd7'
down_revision: Union[str, Sequence[str], None] = 'd6980dd4a9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy_node_topic_terms',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['taxonomy_nodes.id'], ),
    sa.PrimaryKeyConstraint('node_id', 'term')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxonomy_node_topic_terms')
    # ### end Alembic commands ###
