"""baseline schema

Revision ID: 5b8fd10e3c12
Revises: 
Create Date: 2026-03-30 10:18:21.337876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8fd10e3c12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('root_path', sa.String(length=1024), nullable=False),
    sa.Column('added', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('model_provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_name', 'model_provider', 'model', 'prompt_version')
    )
    op.create_table('documents',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('normalised_name', sa.String(length=512), nullable=True),
    sa.Column('llm_enriched_name', sa.String(length=512), nullable=True),
    sa.Column('metadata_title', sa.String(length=512), nullable=True),
    sa.Column('metadata_author', sa.String(length=512), nullable=True),
    sa.Column('metadata_creator', sa.String(length=512), nullable=True),
    sa.Column('metadata_created', sa.String(length=128), nullable=True),
    sa.Column('metadata_modified', sa.String(length=128), nullable=True),
    sa.Column('metadata_extra_json', sa.JSON(), nullable=False),
    sa.Column('languages_json', sa.JSON(), nullable=False),
    sa.Column('is_digital', sa.Boolean(), nullable=False),
    sa.Column('toc_valid', sa.Boolean(), nullable=True),
    sa.Column('toc_invalid_reason', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=32), nullable=True),
    sa.Column('force_extracted', sa.Boolean(), nullable=False),
    sa.Column('first_seen_job', sa.String(length=64), nullable=True),
    sa.Column('last_seen_job', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['first_seen_job'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['last_seen_job'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('sha256')
    )
    op.create_table('document_paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('rel_path', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['sha256'], ['documents.sha256'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rel_path'),
    sa.UniqueConstraint('sha256', 'rel_path')
    )
    op.create_table('document_toc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sha256'], ['documents.sha256'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_toc_sha256'), 'document_toc', ['sha256'], unique=False)
    op.create_table('file_stats',
    sa.Column('rel_path', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=False),
    sa.Column('last_scanned_job', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['last_scanned_job'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['sha256'], ['documents.sha256'], ),
    sa.PrimaryKeyConstraint('rel_path')
    )
    op.create_index(op.f('ix_file_stats_sha256'), 'file_stats', ['sha256'], unique=False)
    op.create_table('llm_document_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('suggested_file_name', sa.String(length=512), nullable=True),
    sa.Column('suggested_author', sa.String(length=512), nullable=True),
    sa.Column('suggested_publisher', sa.String(length=512), nullable=True),
    sa.Column('suggested_edition', sa.String(length=256), nullable=True),
    sa.Column('suggested_labels_json', sa.JSON(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['sha256'], ['documents.sha256'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', 'prompt_id')
    )
    op.create_index(op.f('ix_llm_document_suggestions_prompt_id'), 'llm_document_suggestions', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_llm_document_suggestions_sha256'), 'llm_document_suggestions', ['sha256'], unique=False)
    op.create_table('llm_taxonomy_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('suggested_taxonomy_path', sa.String(length=1024), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['sha256'], ['documents.sha256'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', 'prompt_id')
    )
    op.create_index(op.f('ix_llm_taxonomy_suggestions_prompt_id'), 'llm_taxonomy_suggestions', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_llm_taxonomy_suggestions_sha256'), 'llm_taxonomy_suggestions', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_taxonomy_suggestions_sha256'), table_name='llm_taxonomy_suggestions')
    op.drop_index(op.f('ix_llm_taxonomy_suggestions_prompt_id'), table_name='llm_taxonomy_suggestions')
    op.drop_table('llm_taxonomy_suggestions')
    op.drop_index(op.f('ix_llm_document_suggestions_sha256'), table_name='llm_document_suggestions')
    op.drop_index(op.f('ix_llm_document_suggestions_prompt_id'), table_name='llm_document_suggestions')
    op.drop_table('llm_document_suggestions')
    op.drop_index(op.f('ix_file_stats_sha256'), table_name='file_stats')
    op.drop_table('file_stats')
    op.drop_index(op.f('ix_document_toc_sha256'), table_name='document_toc')
    op.drop_table('document_toc')
    op.drop_table('document_paths')
    op.drop_table('documents')
    op.drop_table('prompts')
    op.drop_table('jobs')
    # ### end Alembic commands ###
