"""added tree node models

Revision ID: 8f71667bca52
Revises: b7d9c1e3f4a5
Create Date: 2026-04-11 17:43:07.008487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f71667bca52'
down_revision: Union[str, Sequence[str], None] = 'b7d9c1e3f4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name'),
    sa.UniqueConstraint('path')
    )
    op.create_table('taxonomy_assignments',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('assigned_child_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_child_id'], ['taxonomy_nodes.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['taxonomy_nodes.id'], ),
    sa.ForeignKeyConstraint(['sha256'], ['documents.sha256'], ),
    sa.PrimaryKeyConstraint('node_id', 'sha256')
    )
    op.create_table('taxonomy_node_documents',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['taxonomy_nodes.id'], ),
    sa.ForeignKeyConstraint(['sha256'], ['documents.sha256'], ),
    sa.PrimaryKeyConstraint('node_id', 'sha256')
    )
    op.drop_column('llm_taxonomy_suggestions', 'suggested_new_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_taxonomy_suggestions', sa.Column('suggested_new_path', sa.VARCHAR(length=1024), nullable=True))
    op.drop_table('taxonomy_node_documents')
    op.drop_table('taxonomy_assignments')
    op.drop_table('taxonomy_nodes')
    # ### end Alembic commands ###
