"""drop taxonomy node status

Revision ID: 9b17820262e4
Revises: ef4c9502ae67
Create Date: 2026-04-11 23:53:20.115122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b17820262e4'
down_revision: Union[str, Sequence[str], None] = 'ef4c9502ae67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxonomy_nodes', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxonomy_nodes', sa.Column('status', sa.VARCHAR(length=32), nullable=False))
    # ### end Alembic commands ###
