"""add taxonomy assignment reasoning summary

Revision ID: d6980dd4a9a6
Revises: 9b17820262e4
Create Date: 2026-04-12 10:25:33.934127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6980dd4a9a6'
down_revision: Union[str, Sequence[str], None] = '9b17820262e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxonomy_assignments', sa.Column('reasoning_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxonomy_assignments', 'reasoning_summary')
    # ### end Alembic commands ###
